### PR TITLE
Feature/open file dialog

### LINKED ISSUE #61: Allow to select path to local image through UI
**Feature description**

Providing the path to the a local image in Skyimager is a bit of a pain. It would be easier to allow the selection through a popup that allows to click through the filesystem to find the location of the image. 

**Is your feature request related to a problem? Please describe.**
Finding and correctly inputting path of the local image is tiresome. 

**Describe the solution you'd like**
A popup like this 

Bildschirmfoto 2020-11-06 um 21 16 01

### PR DESCRIPTION
**Pull request by i-hate-nicknames**
Fixes #61 

Changes:
- Adds open file button to pick image file

Does this change need to mentioned in CHANGELOG.md?

No

### CODE REVIEW

**Review by jdknives — COMMENTED** [review]
Cool. The change to the new version might have screwed with the theme of the UI though. 
Bildschirmfoto 2020-11-11 um 16 10 29

**Comment by i-hate-nicknames** [comment]
Weird, it actually looks much sharper on linux after update. Does it print anything to the log?

**Review by Darkren — APPROVED** [review]

**Comment by jdknives** [comment]
@i-hate-nicknames it does not print anything to the logs. I dont mind keeping it in this theme to be honest.

**Comment by i-hate-nicknames** [comment]
It may be taking some system color settings. I have some default colors set up by my distro, I believe in form of Xorg variables. Now that I think about it, the colors in builder are very close to those set there.

**Pull request merged**
