### PR TITLE
Skyraspian support enhancement

### LINKED ISSUE #78: Skyraspian support
**Feature description**

Asxtree made a port of Skybian to Raspian for RPis. We should

- add build targets for Skyraspian
- add GUI support for Skyraspian in the Skyimager
- automatically release both Skybian and Skyraspian

**Is your feature request related to a problem? Please describe.**
RPi users need to build and install themselves.

### PR DESCRIPTION
**Pull request by asxtree**
Fixes #78

Changes:

 - Added build targets for Skyraspian

Does this change need to mentioned in CHANGELOG.md?

Yes

### CODE REVIEW

**Comment by i-hate-nicknames** [comment]
Great job there. We are currently in the process of migrating to new skywire version, which uses a single binary for both visor and hypervisor. Would you mind rewriting it in the same way? Here is a PR with the changes https://github.com/skycoin/skybian/pull/73. The build is largely untouched and for the most part it's a different firstrun script

**Comment by asxtree** [comment]
Thanks, sure I’ll make the necessary changes in the firstrun script and
build.conf and test it then I’ll update the branch

**Comment by asxtree** [comment]
Updated the code for the one binary migration. In the end it was more than the firstrun script but should be ok now and ive also tested the image using the v0.2.0 skyimager with wifi and lan

**Comment by i-hate-nicknames** [comment]
Works for me, great job. One small note `static/skywire-hypervisor.service` should be removed for clarity, it gets copied into the image.

**Comment by asxtree** [comment]
Not needed anymore as all the enhancements were pushed already in PR#98

**Pull request closed without merging**
