### PR TITLE
Feature/raspbian image gui

### PR DESCRIPTION
**Pull request by i-hate-nicknames**
Fixes #

Changes:
- Add raspbian image selector to skyimager-gui

Does this change need to mentioned in CHANGELOG.md?

No

### CODE REVIEW

**Comment by jdknives** [comment]
Running into 

```
[2021-01-19T15:09:12-03:00] DEBUG [skyimager]: Set: fg.visors =
[2021-01-19T15:09:12-03:00] DEBUG [skyimager]: Set: fg.visors = 1
panic: runtime error: index out of range [0] with length 0

goroutine 36 [running]:
github.com/skycoin/skybian/pkg/imager.(*FyneUI).build(0xc0000e06e0)
	/app/pkg/imager/fyne.go:264 +0x149f
github.com/skycoin/skybian/pkg/imager.(*FyneUI).Page3.func3.1(0xc001701701)
	/app/pkg/imager/fyne_pages.go:341 +0x3d
fyne.io/fyne/dialog.(*dialog).hideWithResponse(0xc001a86100, 0xc001a7a801)
	/go/pkg/mod/fyne.io/fyne@v1.4.0/dialog/base.go:195 +0x5d
fyne.io/fyne/dialog.NewConfirm.func1()
	/go/pkg/mod/fyne.io/fyne@v1.4.0/dialog/confirm.go:33 +0x2f
fyne.io/fyne/widget.(*Button).Tapped(0xc001a7a840, 0xc00161c3e0)
	/go/pkg/mod/fyne.io/fyne@v1.4.0/widget/button.go:197 +0x97
fyne.io/fyne/internal/driver/glfw.(*window).mouseClicked.func5()
	/go/pkg/mod/fyne.io/fyne@v1.4.0/internal/driver/glfw/window.go:734 +0x38
fyne.io/fyne/internal/driver/glfw.(*window).runEventQueue(0xc00020e000)
	/go/pkg/mod/fyne.io/fyne@v1.4.0/internal/driver/glfw/window.go:1152 +0x7a
created by fyne.io/fyne/internal/driver/glfw.(*gLDriver).createWindow.func1
	/go/pkg/mod/fyne.io/fyne@v1.4.0/internal/driver/glfw/window.go:1176 +0x103
```
	
When trying to build Skybian images with Wifi enabled.

**Comment by jdknives** [comment]
@i-hate-nicknames this is independent of the options chosen. It always fails when I try to build.

**Review by jdknives — APPROVED** [review]
Good job. This works now afaict. We'll only need to remove Skyraspbian 64bit for now as @asxtree will need some time to implement that. We can just comment it out imo.

**Comment by i-hate-nicknames** [comment]
It seems that the names for images have changed in this PR: https://github.com/skycoin/skybian/pull/98
I updated to the names used in the said PR. Has to be tested on an actual release

**Pull request merged**
