### PR TITLE
Update fyne to v2

### PR DESCRIPTION
**Pull request by ersonp**
Fixes #

Changes:
- Updated `fyne` to `v2`
- Changed depreciated  functions
- Changed from `github.com/lucor/fyne-cross` to `github.com/fyne-io/fyne-cross`

Does this change need to mentioned in CHANGELOG.md?

No

### CODE REVIEW

**Comment by jdknives** [comment]
Running into /

```
usr/bin/docker run --rm -t -w /app -v /home/work/go/src/github.com/skycoin/skybian:/app -v /home/work/.cache/fyne-cross:/go -e CGO_ENABLED=1 -e GOCACHE=/go/go-build -e GOOS=linux -e GOARCH=amd64 -e CC=gcc -e fyne_uid=1000 lucor/fyne-cross:1.5.0 go build -ldflags ' -w -s' -o /app/fyne-cross/bin/linux-amd64/skyimager-gui -v ./cmd/skyimager-gui
build github.com/skycoin/skybian/cmd/skyimager-gui: cannot load embed: malformed module path "embed": missing dot in first path element
Could not build for linux/amd64: exit status 1
make: *** [Makefile:63: build-skyimager-gui] Fehler 1
```

**Comment by mrpalide** [comment]
New Changes:

- ~[x] Add simple `cache` process to reduce getting image base urls from github~
- [x] Change working directory from a simple text field to folder chooser by click on it
- [x] `Cancel` button not work during download base image

**Comment by jdknives** [comment]
> New Changes:
> 
> * [x]  Add simple `cache` process to reduce getting image base urls from github
> * [ ]  Add a button to reload urls more than once manually
> * [x]  Change working directory from a simple text field to folder chooser by click on it
> * [ ]  `Cancel` button not work during download base image

@mrpalide some good ideas but not relevant for now. Please do not implement features that are not requested or were not implemented before. Please get the download cancel working button working and make the tests pass. Cache and URl reloading was not supported previously iirc.

**Comment by alexadhy** [comment]
For cancel button:

Can't we just spawn another window in fyne ? then just add that progress bar and that cancel button to it, while disabling forms and button on the first window? just an idea

since that cancel button will not be called until *after* the progress bar finished, from the callstack, and ~~that's I believe is the issue from the library itself~~ the issue is the `Download` function is blocking UI event thread from running. 

Since there's not a lot of differences between decoration-less Window and dialogs, I made it work with `SplashWindow` (mine is a 15 minutes bad hack)


https://user-images.githubusercontent.com/72057554/135474816-9117bff9-c46d-467b-8f10-0c268eb10b9b.mp4

**Pull request merged**
